[package]
name = "rocket_note"
version = "0.1.0"
authors = ["Zhong Wei <zhongwei99@163.com>"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.10"